# Star Citizen and a Pre-Modern Pursuit of the Aesthetic

Star Citizen is a mass multiplayer online game set 900 years in the future. As a narrative, it explores concepts such as exploration and colonization. Although human societies are not in a position within this imagined future to colonize other alien civilizations, there are similar themes explored through the various narrative arcs such as indentured servitude, civil rights, the reach of law. Unlike other games which emphasize their pursuit of such themes, these themes are merely hinted at. 

The center of focus for Star Citizen's developers and audience, is pursuit and definition of agency. Star Citizen is largely an open world game, more akin to the Sims than it is to Mass Effect. The game play it embodies is merely a suggestion. 

The draw for engagement is not a given narrative vision, but rather that it provides a space where a community of players can design and define their own ideal game play. Star Citizen's developers do not invite their community to come and be entertained, nor is the community invited to come and witness the expression of a given narrative. Rather, the community is invited to come and create a shared narrative, to participate through active contribution rather than passive consummation.

## Art as a Video Game

* The artistic and technical sophistication of video games have grown immensely in the last decade.

But here we should focus on the technical growth of video games, and contrast this against the artistic growth.

### *Elder Scrolls: Oblivion*, 2006, *sandbox* game.

* fictional environment
* emphasized agency of the player
* choose to engage in game's narrative
* or to explore dungeons and go on quests
* or refrain from engagement in the game's narrative
* Explores agency

Even in refraining from engagement in the game's narrative, game play, exploring and other basic engagement is emotionally, and aesthetically, rewarding. This kind of engagement is a recent development in video games, although perhaps not as recent in games more generally, if we consider text based games in Dos, or Dungeons and Dragons.

### Grand Theft Auto: *San Andreas*

* Sandbox
* Replaces dungeon exploration and grand quests with criminal activities
* Also explores agency

### *Portal*

* Game play
* Progression
* Goal

## The Arts, and Art Criticism: A survey

### Eighteenth Century and a history

* Aesthetics and 'The Philosophy of Art* was coined at this time

* Art, Fine Art, Beaux Arts:
  * Painting
  * Sculpture
  * Architecture
  * Music
  * Poetry
